planning_space:
  relative_object_position:
    x: 1.0 # expected approximate position of the object to be reconstructed relative to the initial position of the robot
    y: 0.0
    z: 0.0
  base:
    min_radius: 1 # [m] smallest radius around object on which the base may stop (isn't checked if valid, also not by moveit - make sure no collisions occur), default:1m
    max_radius: 0.9 # [m] largest radius around object on which the base may stop, deactivated if lower than min, default:2m
    circle_traj_nr: 1 # number of circles on which the base may move, if zero, 1 is assumed, if 1 the min_radius is used, default:1
    pts_per_circle: 8 # nr of positions on each circle the base may stop, if zero, 8 is assumed, default:8
  link_1:
    min_angle: 1.35 # [rad] as given by youbot, min angle joint_1 may assume, default: 1.35 (to the left)
    max_angle: 1.45 # [rad] as given by youbot, max angle joint_1 may assume, deactivated if smaller than min, default: 1.45
    nr_of_pos: 1 # total number of positions, including min and max, if 1, min angle is used, default:1
  arm:
    min_view_distance: 0.9 # [m] closest distance two viewpoints in arm space may have, default: 0.2
    view_resolution: 10 # [pts/m] number of points generated for the arm space grid: The points of this grid are then filtered to fulfill scan_radius_ & arm_min_view_distance_, default:10
  link_5:
    min_angle: 2.9 # [rad] as given by youbot, min angle for joint 5, default: 2.9 ("even")
    max_angle: 2.9 # [rad] as given by youbot, max angle for joint 5, deactivated if smaller than min, default: 3.4
    nr_of_pos: 1 # total number of positions, including min and max, if 1, min angle is used, default:1