cam_model: Pinhole
cam_width: 752
cam_height: 480
cam_fx:  448.1008985853343
cam_fy: 448.1008985853343
cam_cx: 376.5
cam_cy:  240.5
cam_d0: 0
cam_d1:  0
cam_d2: 0
cam_d3: 0
cam_calib_date: '2014-12-02'
cam_name: gazebo_cam
cam_description: 'Simulated gazebo cam'
